
#include "ADC.h"

void ADC0_init()
{
	SETBIT(ADMUX,REFS0);
	SETBIT(ADCSRA,ADEN);
	SETBIT(ADCSRA,ADPS0);
	SETBIT(ADCSRA,ADPS1);
	SETBIT(ADCSRA,ADPS2);
	
}

uint16_t  ADC0_read()
{
	SETBIT(ADCSRA,ADSC);
	while(READBIT(ADCSRA,ADSC));
	return (ADCL+(ADCH<<8));
}

void ADC1_init()
{
	SETBIT(ADMUX,REFS0);
	SETBIT(ADMUX,MUX0);
	SETBIT(ADCSRA,ADEN);
	SETBIT(ADCSRA,ADPS0);
	SETBIT(ADCSRA,ADPS1);
	SETBIT(ADCSRA,ADPS2);
	
}

uint16_t  ADC1_read()
{
	SETBIT(ADCSRA,ADSC);
	while(READBIT(ADCSRA,ADSC));
	return(ADCL+(ADCH<<8));
}	