


#include "stdMacros.h"

int main(void)
{
	
	CLRBIT( DDRD,DDD2);
	SETBIT( DDRD,DDD7);
	//SETBIT(MCUCR,ISC00);//SET ISC00 AND ISC01 TO GENERATE THE INTERRUPT AT THE RISING EDGE (PAGE 67 DATASHEET) 
	CLRBIT(MCUCR,ISC00);//SET ISC00 AND ISC01 TO GENERATE THE INTERRUPT AT THE RISING EDGE
	SETBIT(MCUCR,ISC01);
	SETBIT(GICR,6);//SET GICR AT Bit 6 TO MAKE INT0: External Interrupt Request 0 Enable
	sei();//SETBIT(SREG,7);
	
    while(1)
    {
        
    }
}
ISR(INT0_vect)
{
	 TOGBIT(PORTD,PD7);
}